import { supabase } from "@/lib/utils";
import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { CheckCircle, AlertTriangle, Loader2, LifeBuoy, FileUp, MessageSquare, BookOpen, Zap } from "lucide-react";
import { AppLayout } from "@/components/AppLayout";
import { apiUrl } from "@/lib/utils";
import { useToast } from "@/hooks/use-toast";

type Diagnostic = {
  name: string;
  status: "ok" | "error" | "pending";
  detail?: string;
};

const faqs = [
  { q: "How do I upload study materials?", a: "Go to Chat or Mentor, click 'Add Material' or the paperclip icon, select your PDF or document, and click Upload. The AI will index it and use it when answering your questions." },
  { q: "How are quizzes generated?", a: "Quizzes are generated by the AI based on your uploaded materials and recent chat topics. You can trigger quiz generation from the Chat page or directly visit the Quiz page." },
  { q: "How does the skill tree work?", a: "The skill tree tracks your progress across subjects. Every quiz, mentor session, and uploaded material contributes to your progress percentages. Visit the Progress page to see your detailed breakdown." },
  { q: "What are tokens?", a: "Tokens are earned by completing quizzes, maintaining streaks, and helping peers in study circles. They show your engagement level and can be used for leaderboard rankings." },
  { q: "Can I use my own study notes?", a: "Yes! LearnEase is built for this. Upload your PDFs, notes, or documents and the AI will answer questions specifically from your material, not generic internet content." },
  { q: "Is my data private?", a: "Yes. Your uploaded materials and conversations are stored securely and only accessible to you. We do not share your learning data with third parties." },
];

const Help = () => {
  const { toast } = useToast();
  const [diagnostics, setDiagnostics] = useState<Diagnostic[]>([
    { name: "Frontend", status: "pending" },
    { name: "Backend", status: "pending" },
    { name: "AI Model", status: "pending" },
  ]);
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [message, setMessage] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [uploadResult, setUploadResult] = useState("");
  const [diagRunning, setDiagRunning] = useState(false);

  const runDiagnostics = async () => {
    setDiagRunning(true);
    const next: Diagnostic[] = [];
    next.push({ name: "Frontend", status: "ok", detail: "Running normally" });
    try {
      const res = await fetch(apiUrl("/"));
      if (res.ok) {
        const js = await res.json();
        next.push({ name: "Backend", status: "ok", detail: `Version ${js.version}` });
      } else {
        next.push({ name: "Backend", status: "error", detail: `HTTP ${res.status}` });
      }
    } catch (e: unknown) {
      next.push({ name: "Backend", status: "error", detail: e instanceof Error ? e.message : String(e) });
    }
    try {
      const res = await fetch(apiUrl("/api/messages"), {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ user: "ping" }),
      });
      if (res.ok) {
        const js = await res.json();
        next.push({ name: "AI Model", status: "ok", detail: js.text?.slice(0, 80) || "OK" });
      } else {
        next.push({ name: "AI Model", status: "error", detail: `HTTP ${res.status}` });
      }
    } catch (e: unknown) {
      next.push({ name: "AI Model", status: "error", detail: e instanceof Error ? e.message : String(e) });
    }
    setDiagnostics(next);
    setDiagRunning(false);
  };

  useEffect(() => { runDiagnostics(); }, []);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!name || !email || !message) {
      toast({ title: "Please fill all fields", variant: "destructive" });
      return;
    }
    setSubmitting(true);
    setTimeout(() => {
      toast({ title: "Support ticket submitted!", description: "We'll get back to you within 24 hours." });
      setName(""); setEmail(""); setMessage("");
      setSubmitting(false);
    }, 1000);
  };

  const handleFileUpload = async () => {
    if (!selectedFile) return;
    if (!supabase) { toast({ title: "Storage not configured", variant: "destructive" }); return; }
    setUploading(true);
    try {
      const filePath = `support-uploads/${Date.now()}_${selectedFile.name}`;
      const { error } = await supabase.storage.from("uploads").upload(filePath, selectedFile, { upsert: true });
      if (error) throw error;
      setUploadResult(`✓ ${selectedFile.name} uploaded successfully.`);
      toast({ title: "File attached to your ticket!" });
      setSelectedFile(null);
    } catch (error: any) {
      toast({ title: "Upload failed", description: error.message, variant: "destructive" });
    } finally {
      setUploading(false);
    }
  };

  return (
    <AppLayout title="Help & Support">
      <div className="p-8 max-w-4xl space-y-8">
        {/* Quick links */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {[
            { icon: MessageSquare, label: "Chat with AI", desc: "Ask anything", href: "/chat" },
            { icon: BookOpen, label: "Materials Guide", desc: "How to upload", href: "/materials" },
            { icon: Zap, label: "Quiz Help", desc: "How quizzes work", href: "/quiz" },
            { icon: LifeBuoy, label: "Community", desc: "Ask peers", href: "/community" },
          ].map(({ icon: Icon, label, desc, href }) => (
            <a key={label} href={href}>
              <Card className="glass border-border/60 hover:border-primary/30 transition-all cursor-pointer group h-full">
                <CardContent className="pt-4 pb-4">
                  <div className="w-9 h-9 rounded-xl bg-primary/10 flex items-center justify-center mb-3 group-hover:bg-primary/20 transition-colors">
                    <Icon className="w-4 h-4 text-primary" />
                  </div>
                  <p className="text-sm font-semibold">{label}</p>
                  <p className="text-xs text-muted-foreground">{desc}</p>
                </CardContent>
              </Card>
            </a>
          ))}
        </div>

        {/* System diagnostics */}
        <Card className="glass border-border/60">
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <CardTitle className="text-sm">System Status</CardTitle>
              <Button size="sm" variant="outline" className="h-7 text-xs" onClick={runDiagnostics} disabled={diagRunning}>
                {diagRunning ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : "Refresh"}
              </Button>
            </div>
          </CardHeader>
          <CardContent>
            <div className="space-y-2">
              {diagnostics.map((d) => (
                <div key={d.name} className="flex items-center gap-3 p-3 glass rounded-xl">
                  {d.status === "ok" ? (
                    <CheckCircle className="w-4 h-4 text-green-500 shrink-0" />
                  ) : d.status === "error" ? (
                    <AlertTriangle className="w-4 h-4 text-red-500 shrink-0" />
                  ) : (
                    <Loader2 className="w-4 h-4 animate-spin text-muted-foreground shrink-0" />
                  )}
                  <div className="flex-1 min-w-0">
                    <span className="text-sm font-medium">{d.name}</span>
                    {d.detail && <p className="text-xs text-muted-foreground truncate">{d.detail}</p>}
                  </div>
                  <Badge
                    variant={d.status === "ok" ? "secondary" : d.status === "error" ? "destructive" : "outline"}
                    className="text-xs shrink-0"
                  >
                    {d.status === "ok" ? "Online" : d.status === "error" ? "Error" : "Checking..."}
                  </Badge>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        {/* FAQ */}
        <Card className="glass border-border/60">
          <CardHeader className="pb-3">
            <CardTitle className="text-sm">Frequently Asked Questions</CardTitle>
          </CardHeader>
          <CardContent>
            <Accordion type="single" collapsible className="w-full">
              {faqs.map((faq, i) => (
                <AccordionItem key={i} value={`faq-${i}`} className="border-border/40">
                  <AccordionTrigger className="text-sm text-left hover:no-underline">{faq.q}</AccordionTrigger>
                  <AccordionContent className="text-sm text-muted-foreground leading-relaxed">{faq.a}</AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </CardContent>
        </Card>

        {/* Contact support */}
        <Card className="glass border-border/60">
          <CardHeader className="pb-3">
            <CardTitle className="text-sm">Contact Support</CardTitle>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleSubmit} className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-1.5">
                  <Label className="text-xs">Name</Label>
                  <Input value={name} onChange={e => setName(e.target.value)} placeholder="Your name" className="h-9" />
                </div>
                <div className="space-y-1.5">
                  <Label className="text-xs">Email</Label>
                  <Input type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="your@email.com" className="h-9" />
                </div>
              </div>
              <div className="space-y-1.5">
                <Label className="text-xs">Message</Label>
                <Textarea value={message} onChange={e => setMessage(e.target.value)} placeholder="Describe your issue..." rows={4} />
              </div>
              <div className="flex items-center gap-3 flex-wrap">
                <input type="file" className="hidden" id="support-file" onChange={e => setSelectedFile(e.target.files?.[0] || null)} />
                <label htmlFor="support-file">
                  <Button type="button" asChild variant="outline" size="sm" className="gap-1.5">
                    <span><FileUp className="w-3.5 h-3.5" /> Attach file</span>
                  </Button>
                </label>
                {selectedFile && (
                  <Button type="button" size="sm" variant="secondary" onClick={handleFileUpload} disabled={uploading}>
                    {uploading ? <Loader2 className="w-3.5 h-3.5 animate-spin mr-1.5" /> : null}
                    Upload {selectedFile.name.slice(0, 20)}
                  </Button>
                )}
                {uploadResult && <span className="text-xs text-green-500">{uploadResult}</span>}
              </div>
              <Button type="submit" disabled={submitting} className="bg-gradient-to-r from-primary to-accent text-white border-0">
                {submitting ? <><Loader2 className="w-4 h-4 mr-2 animate-spin" /> Sending...</> : "Send Message"}
              </Button>
            </form>
          </CardContent>
        </Card>
      </div>
    </AppLayout>
  );
};

export default Help;
